#' Prints an Example of a QualtRics Configuration File to the Console.
#'
#' This function is deprecated; use \code{\link[qualtRics]{qualtrics_api_credentials}} instead.
#'
#' @param ... All arguments for \code{qualtRicsConfigFile}
#'
#' @export
#' @examples
#' \dontrun{
#' # Execute this line to get instructions on how to make a .qualtrics.yml config file.
#' qualtRicsConfigFile()
#' }
#'
qualtRicsConfigFile <- function(...) {

  .Deprecated("qualtrics_api_credentials")

}

#' Retrieve a data frame containing question IDs and labels
#'
#' This function is deprecated; use \code{\link[qualtRics]{survey_questions}}
#' instead.
#' @param ... All arguments for \code{survey_questions}
#'
#' @export
getSurveyQuestions <- function(...) {
  .Deprecated("survey_questions")
  survey_questions(...)
}

#' Download a survey and import it into R
#'
#' This function is deprecated; use \code{\link[qualtRics]{fetch_survey}}
#' instead.
#' @param ... All arguments for \code{fetch_survey}
#'
#' @export
getSurvey <- function(...) {
  .Deprecated("fetch_survey")
  fetch_survey(...)
}

#' Read a CSV file exported from Qualtrics
#'
#' This function is deprecated; use \code{\link[qualtRics]{read_survey}}
#' instead.
#' Reads comma separated CSV files generated by Qualtrics
#' software. The second line containing the variable labels is imported.
#' Repetitive introductions to matrix questions are automatically removed.
#' Variable labels are stored as attributes.
#' @param ... All arguments for \code{\link[qualtRics]{read_survey}}
#'
#' @export
readSurvey <- function(...) {
  .Deprecated("read_survey")
  read_survey(...)
}

#' Retrieve a data frame of all active surveys on Qualtrics
#'
#' This function is deprecated; use \code{\link[qualtRics]{all_surveys}}
#' instead.
#' @export
getSurveys <- function() {
  .Deprecated("all_surveys")
  all_surveys()
}





